import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main style={{ minHeight: "calc(100vh - 160px)", padding: "100px 24px", maxWidth: "800px", margin: "0 auto" }}>
        <h1 className="section-title" style={{ textAlign: "left", marginBottom: "32px", fontSize: "2.5rem" }}>Terms of Service</h1>
        <div className="result-body" style={{ color: "var(--text-secondary)" }}>
          <p><strong>Last Updated:</strong> March 2026</p>
          
          <h2 style={{ marginTop: "32px" }}>1. Acceptance of Terms</h2>
          <p>By accessing or using MoatCheck, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you do not have permission to access the service.</p>
          
          <h2>2. Description of Service</h2>
          <p>MoatCheck is an AI-powered startup idea validation tool. The analysis, feedback, and scores provided by our platform are generated by artificial intelligence models (including GPT-5.4) and algorithms. These insights are for informational and brainstorming purposes only.</p>
          
          <h2>3. Not Investment Advice</h2>
          <p><strong>CRITICAL NOTICE:</strong> MoatCheck DOES NOT provide financial, legal, investment, or business advisory services. A high "Moat Score" or positive verdict does not guarantee business success, and a "No-Go" verdict does not mean an idea will fail. You should independently verify all information before making any business decisions or investments.</p>
          
          <h2>4. User Data & Uploads</h2>
          <p>When you input your startup idea or upload Pitch Decks, you retain all rights to your intellectual property. We use your inputs solely to generate your personal analysis report during your active session.</p>
          
          <h2>5. Limitation of Liability</h2>
          <p>In no event shall MoatCheck, its founders, or Aarsh Innovations LLC be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your use of the service or reliance on the AI-generated analysis.</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
